# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-11 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('hostname', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('sity', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=200)),
                ('node_type', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
