# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-11 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nodes',
        ),
    ]
