# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-11 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_nodes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nodes',
        ),
    ]
