# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-11 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_delete_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=300)),
                ('hostname', models.CharField(max_length=300)),
                ('region', models.CharField(max_length=300)),
                ('sity', models.CharField(max_length=300)),
                ('site', models.CharField(max_length=1500)),
                ('description', models.TextField()),
            ],
        ),
    ]
