# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Region')),
            ],
        ),
        migrations.AlterField(
            model_name='nodes',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='site',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Sity'),
        ),
    ]
