# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20170927_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
        migrations.RemoveField(
            model_name='region',
            name='code',
        ),
        migrations.RemoveField(
            model_name='site',
            name='code',
        ),
        migrations.RemoveField(
            model_name='sity',
            name='code',
        ),
    ]
