# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20170927_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iflag',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='country',
            name='name_local',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='region',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='site',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='sity',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
