# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20170927_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='name_local',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='site',
            name='name_local',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sity',
            name='name_local',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='sity',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
